name: Terraform infra & deploy
on:
    workflow_dispatch:
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: checkout code 
              uses: actions/checkout@v6
            - name: azure login
              uses: azure/login@v1
              with:
                creds: ${{ secrets.AZURE_SECRET }}
            # - name: setup terraform
            #   uses: hashicorp/setup-terraform@v3
            # - name: terraform init
            #   working-directory: Terraform
            #   run: terraform init
            # - name: terraform apply
            #   working-directory: Terraform
            #   run: terraform apply -auto-approve
            - name: setup dotnet              # dotnet install
              uses: actions/setup-dotnet@v6
              with:
                dotnet-version: '10.0.x'
            - name: restore dependencies
              run: |
                # cd UrbanCompanySaloon
                dotnet restore
            - name: publish
              run: |
                # cd UrbanCompanySaloon        # i dont have urbancompanysaloon folder in the main folder.
                dotnet publish -c Release -o publish
            - name: show repo structure
              run: |
                ls -R
            - name: deploy to azure
              uses: azure/webapps-deploy@v2
              with:
                app-name: ucwebapp20
                package: ./publish

              
        




          